apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: portainer/portainer-ee
  newTag: 2.15.1
resources:
- serviceaccount.yaml
- rbac.yaml
- statefulset.yaml
- service.yaml
- virtualservice.yaml