apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sabnzbd
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: sabnzbd
  name: sabnzbd-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  serviceName: sabnzbd-service
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
      - env:
        - name: UID
          value: "999"
        - name: GID
          value: "999"
        - name: TZ
          value: America/Chicago
        image: linuxserver/sabnzbd:amd64-latest
        imagePullPolicy: Always
        name: sabnzbd
        ports:
        - containerPort: 8080
          name: sonarr
        volumeMounts:
        - mountPath: /config
          name: sabnzbd-config
          subPath: config
        - mountPath: /mnt/NAS
          name: nfs-emby
        - mountPath: /mnt/downloads
          name: nfs-k8
          subPath: downloads
      terminationGracePeriodSeconds: 10
      volumes:
      - name: nfs-k8
        persistentVolumeClaim:
          claimName: nfs-k8c
      - name: nfs-emby
        persistentVolumeClaim:
          claimName: nfs-embyc
  volumeClaimTemplates:
  - metadata:
      name: sabnzbd-config
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
