apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-config
data:
  WAL_S3_BUCKET: postgresql
  WAL_BUCKET_SCOPE_PREFIX: ""
  WAL_BUCKET_SCOPE_SUFFIX: ""
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  BACKUP_SCHEDULE: '00 12 * * *'
  AWS_ACCESS_KEY_ID: "postgresql"
  AWS_SECRET_ACCESS_KEY: ""
  AWS_S3_FORCE_PATH_STYLE: "true"
  AWS_ENDPOINT: http://minio.apps.svc.cluster.local:9000
  AWS_REGION: de01
  WALG_DISABLE_S3_SSE: "true"
  BACKUP_NUM_TO_RETAIN: "5"
  # CLONE_USE_WALG_RESTORE: "true"
  # CLONE_AWS_ACCESS_KEY_ID: "postgres_user"
  # CLONE_AWS_SECRET_ACCESS_KEY : ""
  # CLONE_AWS_ENDPOINT: http://minio.apps.svc.cluster.local:9000
  # CLONE_AWS_REGION: de01
  # CLONE_METHOD: CLONE_WITH_WALE
  # CLONE_WAL_BUCKET_SCOPE_PREFIX: ""
  # CLONE_WAL_S3_BUCKET: postgresql
  # CLONE_AWS_S3_FORCE_PATH_STYLE: "true"
  # CLONE_TARGET_TIME: "2022-12-31T16:00:00-06:00"
  # CLONE_SCOPE: acid-cluster