apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: redis-ha-haproxy-dtrl
  namespace: redis
spec:
  host: redis-ha-haproxy.redis.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE