apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sentinel-secret
spec:
  encryptedData:
    sentinel-password: AgCAs2oPAq10djEBkiPKR825vRFEqfOAcbmo3I9u9RNFKbXCGH+Zve32ChPW7IdmIlc5hkxUD+6pfUlV79L0rLrHsoJrIBi31pQQUW6Po8olw3APYk4q+RJHYYQ/29Ak+dNyniKQAJHxQbivmz2j9tw1i+hNWi03bnHD7C/DcsZd4u/5YG1NE/6YGr/LV9w2K+OznojlSg8YMKqYPlG7sVzShhZCZfZ8SqZmnETKijit433rWDkMq5yB0dFNfTaQtNQs+b/ZKKXtsOjTOCL0uRnWAZcib9bEok3ut1peCCJE5vMmM4m3L7jBTLf+90QlHaRfa6CPI0gcgY9L0DmL/ld+dET0L5qUDzTJjXELXwIHJ1dfdPTOVNuso+TQsWXy+HU7zT+80kOeUz/SggHtTnH6cpT6EnORwuPsBMWYU+TGUDTPp5pPF4eai3p4ykoMlMagP+7sKL9Z90EgjJj7DChOmvRQ0R7KkX/Yc8tnXLTyXSZwAaXQBj5ZPA0brNiCWvZSaHcDCFdx58DkkdbZQLI8teRYFkrSSa2nOs6Ndws2WQlDZIpKDVs/u8E3sUDjlir53epb5FNwnX5N6v3U+szVPZSkVOWtEXmOsqNNA2Y8pI/dUzLQDxJkG9sFc98/SS6Qy+XQfzSsP+3XUvyPWRfl/5tdX7V+3qzEeUC7IP2Z/YrslOggFoZYiAcFGg6/HOb5UEsbU4gJVdvxb1TSeDt+z3WKqWo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sentinel-secret

