kind: Service
apiVersion: v1
metadata:
  name: udpxy-service
spec:
  selector:
    app: udpxy
  ports:
  - protocol: TCP
    port: 4022
    targetPort: 4022
  - protocol: UDP
    port: 4022
    targetPort: 4022
  type: LoadBalancer