apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: linuxserver/readarr
  newTag: amd64-develop
resources:
- deployment.yaml
- service.yaml
- virtualservice.yaml
- destinationrule.yaml