apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-cluster
spec:
  teamId: "acid"
  volume:
    size: 2Gi
  numberOfInstances: 2
  users:
    authentik.authentik:  # database owner
    - superuser
    - createdb
    # authentik_user: []
  databases:
    authentik: authentik  # dbname: owner
  postgresql:
    version: "14"