apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  dex.config: |
      connectors:
      - config:
          issuer: https://auth.secfam.cloud/application/o/argocd/
          clientID: 7f63d34f6b1a665923cdc92cd1b4fcfa2e3f8671
          clientSecret: $dex.authentik.clientSecret
          insecureEnableGroups: true
          scopes:
            - openid
            - profile
            - email
            - groups
        name: authentik
        type: oidc
        id: authentik