apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

bases:
  - ../../base

resources:
- serviceaccount.yaml
- configmap.yaml
- rbac.yaml
- clusterrolebinding.yaml