apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-cm
data:
  emailusetls: "true"
  emailport: "587"
  errorreportingenabled: "true"
  redishost: "redis-ha-server-0.redis-ha.redis.svc.cluster.local"
