apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: authentik-virtual-service
  namespace: authentik
spec:
  hosts:
  - "auth.secfam.cloud"
  gateways:
  - default/istio-gateway
  http:
  - match:
    - uri:
        prefix: /
    - uri:
        regex: ^\/[^\.]+.*
    route:
    - destination:
        port:
          number: 9090
        host: authentik.authentik.svc.cluster.local