kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-repo-server
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: argocd-repo-server
  apiGroup: ""
roleRef:
  kind: Role
  name: argocd-repo-server
  apiGroup: ""