apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: apps
  source:
    repoURL: https://github.com/hooray4me/cluster1.git
    path: apps/sabnzbd/overlays/prod
    targetRevision: HEAD
  destination:
    namespace: media
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: -1
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m