apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: linuxserver/prowlarr
  newTag: latest

namespace: media

bases:
  - ../../base

resources:
- virtualservice.yaml
- destinationrule.yaml