apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-operator

resources:
  - namespace.yaml
  - sealed-postgres-operator.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/v1.8.2/manifests/configmap.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/v1.8.2/manifests/operator-service-account-rbac.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/v1.8.2/manifests/postgres-operator.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/v1.8.2/manifests/api-service.yaml

patchesStrategicMerge:
  - configmap.yaml