apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- projects/core.yaml
- projects/cluster.yaml
- projects/apps.yaml
- projects/monitoring.yaml
- projects/networking.yaml
- core/namespaces.yaml
- core/argocd.yaml
- core/virtualservice.yaml
- core/destinationrule.yaml
- apps/applications.yaml