apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Applications Example Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: apps
    server: https://kubernetes.default.svc
  - namespace: media
    server: https://kubernetes.default.svc
  - namespace: authentik
    server: https://kubernetes.default.svc
  - namespace: portainer
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  - namespace: databases
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false