apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr-statefulset
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  serviceName: sonarr-service
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - image: linuxserver/sonarr:amd64-latest
        name: sonarr
        imagePullPolicy: Always
        ports:
        - containerPort: 8989
          name: sonarr
        env:
        - name: UID
          value: "999"
        - name: GID
          value: "999"
        - name: TZ
          value: America/Chicago
        volumeMounts:
        - mountPath: /config
          name: sonarr-config
          subPath: config
        - mountPath: /mnt/NAS
          name: nfs-emby-media
        - mountPath: /mnt/downloads
          subPath: downloads
          name: nfs-k8-media
      terminationGracePeriodSeconds: 10
      volumes:
      - name: nfs-k8-media
        persistentVolumeClaim:
           claimName: nfs-k8c
      - name: nfs-emby-media
        persistentVolumeClaim:
          claimName: nfs-embyc
  volumeClaimTemplates:
  - metadata:
      name: sonarr-config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi