apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-db
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - kubernetes.io/pv-protection
  # annotations:
  #   argocd.argoproj.io/sync-wave: "1"
spec:
  project: apps
  source:
    repoURL: https://github.com/hooray4me/cluster1.git
    path: apps/authentik-db/overlays/prod
    targetRevision: HEAD
  destination:
    namespace: authentik
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    # - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    # retry:
    #   limit: -1
    #   backoff:
    #     duration: 20s
    #     factor: 2
    #     maxDuration: 15m