apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: xteve-statefulset
  labels:
    app: xteve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xteve
  serviceName: xteve-service
  template:
    metadata:
      labels:
        app: xteve
    spec:
      containers:
      - image: alturismo/xteve:latest
        name: xteve
        imagePullPolicy: Always
        ports:
        - containerPort: 34400
          name: xteve
        env:
        - name: UID
          value: "999"
        - name: GID
          value: "999"
        - name: TZ
          value: America/Chicago
        volumeMounts:
        - mountPath: /config
          name: xteve
          subPath: config
        - mountPath: /root/.xteve
          name: xteve
          subPath: root
        - mountPath: /tmp/xteve
          name: xteve
          subPath: tmp
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: xteve
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi