apiVersion: v1
kind: Service
metadata:
  name: dashy-service
spec:
  ports:
  - nodePort: 30078
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dashy
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dashy
    argocd.argoproj.io/instance: dashy
  name: dashy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
      - image: lissy93/dashy:latest
        imagePullPolicy: IfNotPresent
        name: sonarr
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
        volumeMounts:
        - mountPath: /app/public
          name: nfs-k8
          subPath: dashy/public
        - mountPath: /app/public/item-icons/icons
          name: nfs-k8
          subPath: dashy/icons
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs-k8
        persistentVolumeClaim:
          claimName: nfs-k8c
