apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

bases:
  - ../../base

resources:
- serviceaccount.yaml
- configmap.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- role.yaml
- rolebinding.yamll
- virtualservice.yaml