apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: portainer
    app.kubernetes.io/name: portainer
    app.kubernetes.io/version: ce-latest-ee-2.15.1
  name: portainer-sa-clusteradmin
  namespace: portainer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: portainer
    app.kubernetes.io/name: portainer
    app.kubernetes.io/version: ce-latest-ee-2.15.1
  name: portainer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: portainer-sa-clusteradmin
  namespace: portainer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: portainer
    app.kubernetes.io/name: portainer
    app.kubernetes.io/version: ce-latest-ee-2.15.1
    io.portainer.kubernetes.application.stack: portainer
  name: portainer
  namespace: portainer
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: https
    port: 9443
    protocol: TCP
    targetPort: 9443
  - name: edge
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: portainer
    app.kubernetes.io/name: portainer
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: portainer
    app.kubernetes.io/name: portainer
    app.kubernetes.io/version: ce-latest-ee-2.15.1
    io.portainer.kubernetes.application.stack: portainer
  name: portainer
  namespace: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: portainer
      app.kubernetes.io/name: portainer
  serviceName: portainer
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: portainer
        app.kubernetes.io/name: portainer
    spec:
      containers:
      - env:
        - name: TIME_ZONE
          value: America/Chicago
        image: portainer/portainer-ee:2.15.1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 9443
            scheme: HTTPS
        name: portainer
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        - containerPort: 9443
          name: https
          protocol: TCP
        - containerPort: 8000
          name: tcp-edge
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 9443
            scheme: HTTPS
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: portainer-data
      nodeSelector: {}
      serviceAccountName: portainer-sa-clusteradmin
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: portainer-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
