apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: minio-secrets
  namespace: apps
spec:
  encryptedData:
    root-password: AgAjOghxzH32ms30d4iUfAVzuGHminBSK7w568PBDTp2d2ZjzNsxsasGAcT0xp0vCa/7mpV60HizzC2q4WYJjowTRvSTD2czpT6XnrZ+4iKo6FlCUI+5U0jMl3u1JEpwsUgaNgayqoF7Fx8NHACikdjJP7CT2BCQJzlb47I41C8x/+U9PdXvjxZKlr45c6e2AYF6VmAESIBQ2T2df87qPnBuA0el/MPPYoTWpjy0Hl0e8eNu7fQIlHTPJNqaxFuBpjEh0cSBij9W6E+oOW6qDU5sWZMxno9zX3eD7HkuVdXIFbgfAgSlVAPfnfSzoHnDpP5gI864QWZ7CwLPK8Dp7A1nagEay+ecANE2sNsjw6WsXSJ0r2GZiFxFukt/qbf3EUt8XqF4G1+uTXS/GwgiS5RqsXzxVTP5+XRNc4fkFN+nEWzTkSiDiBPnVxiRNvQg2oC+CaPmuyY5uCYp3MWShSGdxCnLQFDe+szoTTzCs0BPbeklVuUISQFyBvPNVCxI3tIb/w7DUILMpc2POTUGjIZbPJFXeLSmOcL9frlYq8P15vQ1k+qaF4UkWrcYGztJyHZc78Z2IANOEycAV+4dUyDJky1UctXFqsbkvyuOf0TdCRHNpZd0Q5UcYdxdnbnU2iCb6glzTfSA08ZRYriYURrScoil0dLI50j8u2UYs0o9kCqik4a0jyxoXkZSd2aEQg3TLkc4PaVpnIfAcA==
    root-user: AgBCkGhqeuwBySz8ud1AMz0XFdP41BlTQ6Y9wYpczxFehAZnsqzyMnYsqJTBmK/lU7B1GgNf/WER2qfyb9BAWKZUR5KdlFsQSyld+2odyXHVYqWqWY2Azp5dO3wyJhMK8cmW/4NPcoJk73/jqSC3U3rm4UGuWNTzB2ms3mK/245eyKuIdmltbMbQEc3pObNcwB8kBmSyZbhGroBzBlSGYaexu1LmsE0IIqc+PeHbva6k/hBShXRWk3akJhEpbQqqHZSLRWrixWw32241i90pDK2zRkc3bcMe9upmWIEJ7q+u1uK65Myn3GErRGXx3SX+A9t3rhRsBaRMO1HPurU2gpy/IFJII2X+ZAf9fD0Qv6X4vAA61P13OYmAxrDWY5rIkylJc0nmS3T3uRxkXmeH6C9tuTOnW+X0VWlmFvKUWKaXgGjK/F6WCv5T/7EBDxfrs2d3VnJndd2d5IODFTMuJFK+HBt0naAIep5/BOM5SGIGY51oVf/vY1XhckTSOErj/job0jwOLjbi9mxU7ZIX/JBzboy2EVm7W8f8xI7ywWMNDHOMRXHEY0R9dbgn/6Qfxme0xLz6SZWi0mwXAMLNEy7x4xvJY/Wk6rz3VV7fOBC8a8QMkdEI6w9f5WdXpUIMuF1TfsYO1c4YStDmVOm33enEq/zmPUB9hVlbyPNp+tpUOQHSJ1o7flrJMbTDjnE669bsp+0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: minio-secrets
      namespace: apps

