apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgA21sRINSb/4I7HH6lmDtI9Kz3TeirDBHws5szmKdqq75rt0GhkGyKSmOw2A+/7Y8FgwRswFuBxs9m6870GqCkeMDVSsdeD3ec8i2XbbvrbZH7HBnLZolYiDLpRXj/zbIHP3do5m/nZI0WMubd+y/7mIpH+esMYdLnJ3ylc9E/qqZa4J2uuWUtvNFoJc5CxlqM6Ntr3UDgTiz8QjcadheH6q3I960MwIk6Xi2aphxQWhgoPWx9BSrzn5gTu6m30ZViWZqSPB7S79f+xRkp4SYk3aehUNy9LLc3d/0KjZ9ZSiPX7DJB5KypqoAXqbQ+9zK3Rg+CDKRkfDTVCdyvVu6p+UUVjwxu8W9BlUl6rn2ytqr+/munNk6zS4NgmJFt+OcGrITe9+dLQPDM0QKmNQc8rCqScHav8Acc9rZIlqC7tlYkfyJb9Yu6ZetegXqN/IWIayeBRozq/yWELf6M0UGHY1TSZ391QPUkPXNfhpDDEzjhQQyLBTg3fSvFJN5xCYYlI8WxTcxVH1tw48g+tI/wyDgnC/0yWn4Z6bMxylpxwUN6hzDOULGwvO+3JfZbPeBKWxz9rDtcV4L6gdioJTi6VtbP2Zjkw5S8dDZFNTr/gCOIlDlME5uy3+4iLw0OMaGgwTU6NmBS/lqYS8WYOMPDQYXT8yGLarp612TkwsR/kHlzp4n6zPU86LHD6uuSvOjkbqEVjpreyxinaICrmMMtCKQhI0Y3OhlSFcCcVyUqFAP/1dc/xjj+f
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
    type: Opaque

