apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xteve
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hooray4me/cluster1.git
    targetRevision: HEAD
    path: manifests/xteve/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true