apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-operator

resources:
  # - configmap.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/v1.8.2/ui/manifests/deployment.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/v1.8.2/ui/manifests/ingress.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/v1.8.2/ui/manifests/service.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/v1.8.2/ui/manifests/ui-service-account-rbac.yaml

patches:
  - target:
      kind: Ingress
      name: postgres-operator-ui
    patch: |-
      - op: remove

# patchesStrategicMerge:
#   - patch-env-from.yaml
#   - "ingress.yaml"

# configMapGenerator:
#   - envs:
#       - envs.yaml
#     name: envs