apiVersion: apps/v1
kind: Pod
metadata:
  namespace: postgres-operator
  labels:
    name: postgres-operator-ui
spec:
  template:
    spec:
      containers:
        - name: "*"
          envFrom:
            - configMapRef:
                name: envs