apiVersion: apps/v1
kind: Pod
metadata:
  name: postgres-operator-ui
  namespace: postgres-operator
spec:
  template:
    spec:
      containers:
        - name: postgres-operator-ui
          envFrom:
            - configMapRef:
                name: envs