apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: minio
  releaseName: minio
  namespace: apps
  valuesFile: values.yaml

resources:
- sealed-minio-secrets.yaml
- destinationrule.yaml
# - virtualservice.yaml