apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: core
  source:
    repoURL: https://github.com/hooray4me/cluster1.git
    path: apps/applications
    directory:
      recurse: true
    targetRevision: HEAD
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - ApplyOutOfSyncOnly=false
    - Prune=true