apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: alturismo/xteve
  newTag: latest
resources:
- deployment.yaml
- service.yaml
- virtualservice.yaml
- destinationrule.yaml