apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sealed-github-https-credentials.yaml
- base/projects/core.yaml
- base/projects/cluster.yaml
- base/projects/apps.yaml
- base/projects/monitoring.yaml
- base/projects/networking.yaml
- base/core/namespaces.yaml
- base/core/argocd.yaml
- base/core/virtualservice.yaml
- base/core/destinationrule.yaml
- base/apps/root-app.yaml

- https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.11/manifests/install.yaml

# components:
# - https://github.com/argoproj-labs/argocd-extensions/manifests

patchesJson6902:
- path: overlay/deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1

namespace: argocd
images:
- name: quay.io/argoproj/argocd
  newTag: v2.3.11

patchesStrategicMerge:
#   - overlay/patch-env-from.yaml
  - overlay/argocd-cm.patch.yaml
#   - overlay/argocd-rbac-cm.yaml

# configMapGenerator:
#   - envs:
#       - overlay/nogpg.yaml
#     name: envs